### ISSUE TITLE
Wrong constructor interface in the example

### ISSUE THREAD

**Issue by AllDayAlone** [neofinancial/node-flinks#5]
![image](https://user-images.githubusercontent.com/32430949/118087470-4825be00-b3ce-11eb-96e3-087f6cce81fd.png)
 
The constructor takes 2 string arguments but there is an object in the example

**Comment by AllDayAlone** [comment]
![image](https://user-images.githubusercontent.com/32430949/118088780-40ffaf80-b3d0-11eb-8980-11120449aa13.png)
The following line is wrong too as it returns response object, not directly `requestId`

**Comment by veeru76** [comment]
hey @AllDayAlone  can you please share me how can we access FlinksClient

**Comment by AllDayAlone** [comment]
@veeru76 I do it like that
```
const FlinksClient = require('node-flinks').default;
const flinksService = new FlinksClient(config.flinks.instanceName, config.flinks.clientId);
let response = await flinksService.getAccountsDetail({ requestId });
```

**Comment by iansu** [comment]
This is fixed now. Thanks!
